export const copyDefs = [
  ["Booker storm rifle", "AssaultRifleHeavyW"],
  ["Aalto storm rifle", "AssaultRifleW"],
  ["Storm rifle ammo (7.92mm)", "AssaultRifleAmmo"],
  ["HMG (Malone MK.2)", "MGW"],
  ["Frag grenade (A3 harpa)", "GrenadeW"],
  ["Pistol", "PistolLightW"],
  ["8mm ammo", "PistolAmmo"],
  ["Revolver (Cometa T2-9)", "Revolver"],
  ["Heavy Rifle (Hangman)", "RifleHeavyW"],
  ["Revolver ammo (.44)", "RevolverAmmo"],
  ["Sampo 77", "RifleAutomaticW"],
  ["Carbine (Blakerow)", "RifleLightW"],
  ["Long rifle (Clency Cinder)", "RifleLongW"],
  ["Minicaster (Hawthorne)", "RifleShortW"],
  ["Rifle (Loughcaster)", "RifleW"],
  ["Sniper Rifle (Clency-Raca)", "SniperRifleW"],
  ["Rifle ammo (7.62mm)", "RifleAmmo"],
  ["Shotgun (Brasa)", "Shotgun"],
  ["Shotgun ammo (Buckshot)", "ShotgunAmmo"],
  ["Liar's SMG", "SMGHeavyW"],
  ["SMG (Fiddler)", "SMGW"],
  ["SMG ammo (9mm)", "SMGAmmo"],
  ["Smoke grenade", "SmokeGrenade"],
  ["Gas grenade (Green Ash)", "GreenAsh"],
  ["HMG ammo (12.7mm)", "MGAmmo"],
  ["ATR (Anti Tank Riffle)", "ATRifleW"],
  ["ATR ammo (20mm)", "ATRifleAmmo"],
  ["Mounted bonesaw", "ATRPGTW"],
  ["Bonesaw", "ATRPGW"],
  ["Bonesaw Ammo (ARC/RPG)", "ATRPGAmmo"],
  ["Willows's Bane (flamethrower)", "FlameTorchW"],
  ["Tremola HE rifle grenade", "HELaunchedGrenade"], // @TODO check if correct
  ["Tripod HMG (Ratcatcher)", "MGTW"],
  ["30mm ammo", "MiniTankAmmo"],
  ["Mortar (Cremari)", "Mortar"],
  ["Flare mortar ammo", "MortarAmmoFL"],
  ["Shrapnel mortar ammo", "MortarAmmoSH"],
  ["HE mortar ammo", "MortarAmmo"],
  ["AT Flask Grenade (White Ash)", "ATGrenadeW"],
  ["HE grenade (Mammon)", "HEGrenade"],
  ["Sticky AT Grenade", "StickyBomb"],
  ["Foebreaker", "RPGTW"],
  ["Cutler Launcher", "RpgW"],
  ["Cuttler ammo (RPG)", "RpgAmmo"],
  ["150mm", "HeavyArtilleryAmmo"],
  ["120mm", "LightArtilleryAmmo"],
  ["250mm", "MortarTankAmmo"],
  ["68mm", "ATAmmo"],
  ["40mm", "LightTankAmmo"],
  ["Warhead :)", ""],
  ["Barbed Wire", "BarbedWireMaterials"],
  ["Binoculars", "Binoculars"],
  ["Havoc Charge", "ExplosiveTripod"],
  ["Willows's Bane Ammo (flamethrower)", "FlameBackpackW"],
  ["Listening kit", "ListeningKit"],
  ["Metal Beam", "MetalBeamMaterials"],
  ["Radio backpack", "RadioBackpack"],
  ["Sandbag", "SandbagMaterials"],
  ["Havoc Detonator", "SatchelChargeT"],
  ["Satchel Charge (Aligator)", "SatchelChargeW"],
  ["Shovel", "Shovel"],
  ["Sledge hammer", "SledgeHammer"],
  ["Mine (Abisme AT-99)", "TankMine"],
  ["Tripod", "Tripod"],
  ["Wrench", "WorkWrench"],
  ["Water Bucket", "WaterBucket"],
  ["Bayonet", "Bayonet"],
  ["Gas Mask", "GasMask"],
  ["Gas Mask Filter", "GasMaskFilter"],
  ["Frag Grenade Launcher (Ospreay)", "GrenadeAdapter"],
  ["Radio", "Radio"],
  ["Rocket Booster :)", ""],
  ["Bandage", "Bandages"],
  ["First aid kit", "FirstAidKit"],
  ["Trauma kit", "TraumaKit"],
  ["Blood plasma", "BloodPlasma"],
  ["Soldier supplies", "SoldierSupplies"],
  ["Msups", "MaintenanceSupplies"],
  ["Missing Row", ""], // Row 83 is squashed :(
  ["Specialist's Overcoat", "AmmoUniformW"],
  ["Gunner's Breastplate", "ArmourUniformW"],
  ["Sapper Gear", "EngineerUniformW"],
  ["Physician's Jacket (Medic Uniform)", "MedicUniformW"],
  ["Officer Regalia", "OfficerUniformW"],
  ["Outrider's Mantle", "ScoutUniformW"],
  ["Caovish Parkas (Winter Uniform)", "SnowUniformW"],
  ["Padded Boiler Suit", "TankUniformW"],
  ["Ambulance", "AmbulanceW"],
  ["GAC (O'Brien v.190) Knave", "ArmoredCarTwinW"],
  ["AC (O Brien V 110)", "ArmoredCarW"],
  ["Bus", "BusW"],
  ["HTD (Widow)", "DestroyerTankW"],
  ["FAT (68mm AT gun)", "FieldATDamageW"],
  ["FC (Wolfhound 40mm)", "FieldCannonW"],
  ["FMG (Field Michine Gun - Swallowtail)", "FieldMGW"],
  ["Field Mortar (Falconer 250mm)", "FieldMortarW"],
  ["Flat Bed", "FlatbedTruck"],
  ["HT (Niska Gun Motor Carriage)", "HalfTrackW"],
  ["APC (LPC Mulloy)", "LandingCraftW"],
  ["LT (Devvit MK. III)", "LightTankW"],
  ["Oultaw", "MediumTank2RangeW"],
  ["Silverhand", "MediumTankW"],
  ["Motorbike", "MotorcycleW"],
  ["Fuel truck", "OilTankerW"],
  ["Scout Tank MG (King Spire)", "ScoutTankW"],
  ["LUV (Drummond 100a)", "ScoutVehicleW"],
  ["Dump Truck :)", "TruckDumpW"],
  ["Truck", "TruckW"],
  ["Barge", "Barge"],
  ["Freighter (Ironship)", "Freighter"],
  ["Gunboat 120mm/120mm", "GunboatOffensiveW"],
  ["Gunboat 120mm/MG", "GunboatW"],
  ["Landing Ship (White Whale)", "TroopShip"],
  ["CV", "Construction"],
  ["Crane", "Crane"],
  ["Empty Pallet", "MaterialPlatform"],
  ["Mixer :)", "ConcreteMixer"],
  ["EAT (Stationary AT Cannon)", "EmplacedATW"],
  ["150mm arty", "EmplacedHeavyArtilleryW"],
  ["120mm arty", "EmplacedLightArtilleryW"],
  ["12.7 Inf gun", "EmplacedInfantryW"],
  ["Resource Container :)", "ResourceContainer"],
  ["Big Shipping Container", "ShippingContainer"],
  ["Fuel Container", "FuelContainer"],
  ["Bmats", "Cloth"],
  ["Emats", "Explosive"],
  ["Hemats", "HeavyExplosive"],
  ["Rmats", "Wood"]
]
