export const copyDefs = [
  ["Booker storm rifle", "AssaultRifleHeavyW"],
  ["Aalto storm rifle", "AssaultRifleW"],
  ["Storm rifle ammo (7.92mm)", "AssaultRifleAmmo"],
  ["HMG (Malone MK.2)", "MGW"],
  ["Frag grenade (A3 harpa)", "GrenadeW"],
  ["Pistol", "PistolLightW"],
  ["8mm ammo", "PistolAmmo"],
  ["Revolver (Cometa T2-9)", "Revolver"],
  ["Heavy Rifle (Hangman)", "RifleHeavyW"],
  ["Revolver ammo (.44)", "RevolverAmmo"],
  ["Sampo 77", "RifleAutomaticW"],
  ["Carbine (Blakerow)", "RifleLightW"],
  ["Long rifle (Clency Cinder)", "RifleLongW"],
  ["Minicaster (Hawthorne)", ""],
  ["Rifle (Loughcaster)", "RifleW"],
  ["Sniper Rifle (Clency-Raca)", "SniperRifleW"],
  ["Rifle ammo (7.62mm)", "RifleAmmo"],
  ["Shotgun (Brasa)", "Shotgun"],
  ["Shotgun ammo (Buckshot)", "ShotgunAmmo"],
  ["Liar's SMG", "SMGHeavyW"],
  ["SMG (Fiddler)", "SMGW"],
  ["SMG ammo (9mm)", "SMGAmmo"],
  ["Smoke grenade", "SmokeGrenade"],
  ["Gas grenade (Green Ash)", "GreenAsh"],
  ["HMG ammo (12.7mm)", ""],
  ["ATR (Anti Tank Riffle)", "ATRifle"],
  ["ATR ammo (20mm)", "ATRifleAmmo"],
  ["Mounted bonesaw", "ATRPGTW"],
  ["Bonesaw", "ATRPGW"],
  ["Bonesaw Ammo (ARC/RPG)", ""],
  ["Willows's Bane (flamethrower)", ""],
  ["Tremola HE rifle grenade", ""],
  ["Tripod HMG (Ratcatcher)", ""],
  ["30mm ammo", "MiniTankAmmo"],
  ["Mortar (Cremari)", ""],
  ["Flare mortar ammo", ""],
  ["Shrapnel mortar ammo", ""],
  ["HE mortar ammo", ""],
  ["AT Flask Grenade (White Ash)", "ATGrenadeW"],
  ["HE grenade (Mammon)", "HEGrenade"],
  ["Sticky AT Grenade", "StickyBomb"],
  ["Foebreaker", "RPGTW"],
  ["Cutler Launcher", "RpgW"],
  ["Cuttler ammo (RPG)", "RPGAmmo"],
  ["150mm", "HeavyArtilleryAmmo"],
  ["120mm", "LightArtilleryAmmo"],
  ["250mm", "MortarTankAmmo"],
  ["68mm", "ATAmmo"],
  ["40mm", "LightTankAmmo"],
  ["Warhead :)", ""],
  ["Barbed Wire", "BarbedWireMaterials"],
  ["Binoculars", "Binoculars"],
  ["Havoc Charge", "ExplosiveTripod"],
  ["Willows's Bane Ammo (flamethrower)", ""],
  ["Listening kit", "ListeningKit"],
  ["Metal Beam", "MetalBeamMaterials"],
  ["Radio backpack", "RadioBackpack"],
  ["Sandbag", "SandbagMaterials"],
  ["Havoc Detonator", ""],
  ["Satchel Charge (Aligator)", ""],
  ["Shovel", "Shovel"],
  ["Sledge hammer", "SledgeHammer"],
  ["Mine (Abisme AT-99)", ""],
  ["Tripod", "Tripod"],
  ["Wrench", "WorkWrench"],
  ["Water Bucket", "WaterBucket"],
  ["Bayonet", ""],
  ["Gas Mask", "GasMask"],
  ["Gas Mask Filter", "GasMaskFilter"],
  ["Frag Grenade Launcher (Ospreay)", ""],
  ["Radio", "Radio"],
  ["Rocket Booster :)", ""],
  ["Bandage", ""],
  ["First aid kit", "FirstAidKit"],
  ["Trauma kit", "TraumaKit"],
  ["Blood plasma", "BloodPlasma"],
  ["Soldier supplies", "SoldierSupplies"],
  ["Msups", ""],
  ["Missing Row", ""], // Row 83 is squashed :(
  ["Specialist's Overcoat", ""],
  ["Gunner's Breastplate", ""],
  ["Sapper Gear", "EngineerUniformW"],
  ["Physician's Jacket (Medic Uniform)", ""],
  ["Officer Regalia", ""],
  ["Outrider's Mantle", ""],
  ["Caovish Parkas (Winter Uniform)", ""],
  ["Padded Boiler Suit", "TankUniformW"],
  ["Ambulance", ""],
  ["GAC (O'Brien v.190) Knave", ""],
  ["AC (O Brien V 110)", ""],
  ["Bus", ""],
  ["HTD (Widow)", ""],
  ["FAT (68mm AT gun)", ""],
  ["FC (Wolfhound 40mm)", ""],
  ["FMG (Field Michine Gun - Swallowtail)", ""],
  ["Field Mortar (Falconer 250mm)", ""],
  ["Flat Bed", ""],
  ["HT (Niska Gun Motor Carriage)", ""],
  ["APC (LPC Mulloy)", ""],
  ["LT (Devvit MK. III)", ""],
  ["Oultaw", ""],
  ["Silverhand", ""],
  ["Motorbike", ""],
  ["Fuel truck", ""],
  ["Scout Tank MG (King Spire)", ""],
  ["LUV (Drummond 100a)", ""],
  ["Dump Truck :)", ""],
  ["Truck", "TruckW"],
  ["Barge", ""],
  ["Freighter (Ironship)", ""],
  ["Gunboat 120mm/120mm", ""],
  ["Gunboat 120mm/MG", ""],
  ["Landing Ship (White Whale)", "TroopShip"],
  ["CV", "Construction"],
  ["Crane", "Crane"],
  ["Empty Pallet", "MaterialPlatform"],
  ["Mixer :)", "ConcreteMixer"],
  ["EAT (Stationary AT Cannon)", ""],
  ["150mm arty", ""],
  ["120mm arty", ""],
  ["12.7 Inf gun", ""],
  ["Resource Container :)", ""],
  ["Big Shipping Container", ""],
  ["Fuel Container", "FuelContainer"],
  ["Bmats", "Cloth"],
  ["Emats", "Explosive"],
  ["Hemats", "HeavyExplosive"],
  //["Rmats", ""] Removed due to sheet restrictions on the row after prevent paste :(
]
